// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUAjgI6m_oQpjaASroSVX1GfTjUgk8uQk',
    appId: '1:1029597383653:web:8ae4750c2f0788232cbd0c',
    messagingSenderId: '1029597383653',
    projectId: 'database-11192',
    authDomain: 'database-11192.firebaseapp.com',
    databaseURL: 'https://database-11192-default-rtdb.firebaseio.com',
    storageBucket: 'database-11192.firebasestorage.app',
    measurementId: 'G-JVNE0JGZBQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEuNPMmAkXQsjEc4KFQredPeCR4V9lYX0',
    appId: '1:1029597383653:android:5db79b3cdd4ffa492cbd0c',
    messagingSenderId: '1029597383653',
    projectId: 'database-11192',
    databaseURL: 'https://database-11192-default-rtdb.firebaseio.com',
    storageBucket: 'database-11192.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDV4JoQi-9PB4I48n21qOEvqP1GdNJlpUY',
    appId: '1:1029597383653:ios:7288247dbd1f95e62cbd0c',
    messagingSenderId: '1029597383653',
    projectId: 'database-11192',
    databaseURL: 'https://database-11192-default-rtdb.firebaseio.com',
    storageBucket: 'database-11192.firebasestorage.app',
    iosBundleId: 'com.example.camApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDV4JoQi-9PB4I48n21qOEvqP1GdNJlpUY',
    appId: '1:1029597383653:ios:7288247dbd1f95e62cbd0c',
    messagingSenderId: '1029597383653',
    projectId: 'database-11192',
    databaseURL: 'https://database-11192-default-rtdb.firebaseio.com',
    storageBucket: 'database-11192.firebasestorage.app',
    iosBundleId: 'com.example.camApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUAjgI6m_oQpjaASroSVX1GfTjUgk8uQk',
    appId: '1:1029597383653:web:e7ee4ea5d8748ee22cbd0c',
    messagingSenderId: '1029597383653',
    projectId: 'database-11192',
    authDomain: 'database-11192.firebaseapp.com',
    databaseURL: 'https://database-11192-default-rtdb.firebaseio.com',
    storageBucket: 'database-11192.firebasestorage.app',
    measurementId: 'G-HK7G41SPPQ',
  );

}